---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.users
            
      # You can create users.
      users_user_list:
        
        - name: user3
          comment: Michael Buluma
          uid: 1095
          # The `group` and `groups` listed here should exist.
          group: sudo
          # groups: A comma separated string of groups, i.e.:
          # groups: users,wheel
          groups: sudo
          cron_allow: yes
          sudo_options: "ALL=(ALL) NOPASSWD: ALL"
          # Adding an authorized key.
          authorized_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCS+uYM2x03UxGoroQMiE+6LMy8w8RWGaj0mKL5DyEa72hHVGzpjmi083iKFaHbreugKEebXRXaHNKJSf4Nl7AfFFo5ERVkDDE8hbKmdQ3wbW3VrYTdmNFCdC7F3UEWyE+WpxanCcc+wPW2IH36TSC56cEB4Y+XJkgvLozZyG6cnh0Im4g0dtpNz7n3Kyh9j3b5jfPZzpvLwlKCaPwaUxnkt4pv2SELEA5UJDkHbJ31UxwbBMQiaCwpD/XEKu+pOoIeFYcmrfQ1Bcfg5cnCYJCwbX8IQt1Y4XXkkbdgBviSRsbeyseZ637qC6Mjg3+6/byIHNZzGs4dFl8PIIbon6jaqxlhgNc9/hCSa1jvlEwDotE66+DU/LgYMzDTrpWFFxwSGiecRu3zlSIqYLH0Q2XCDQNpoL+is2KIC80qHZAdbFZXhMLqkJ1GaVDGbtrXrjEioipz+BEX6ERdA6DZYqh//kwXI8Hs88chc5eKZMqpKwwD16ELEfXevI2Niwph55M= ruslan@netology"

        - name: user4
          comment: Michael Buluma
          uid: 1096
          # The `group` and `groups` listed here should exist.
          group: sudo
          # groups: A comma separated string of groups, i.e.:
          # groups: users,wheel
          groups: sudo
          cron_allow: yes
          sudo_options: "ALL=(ALL) NOPASSWD: ALL"
          # Adding an authorized key.
          authorized_keys:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCS+uYM2x03UxGoroQMiE+6LMy8w8RWGaj0mKL5DyEa72hHVGzpjmi083iKFaHbreugKEebXRXaHNKJSf4Nl7AfFFo5ERVkDDE8hbKmdQ3wbW3VrYTdmNFCdC7F3UEWyE+WpxanCcc+wPW2IH36TSC56cEB4Y+XJkgvLozZyG6cnh0Im4g0dtpNz7n3Kyh9j3b5jfPZzpvLwlKCaPwaUxnkt4pv2SELEA5UJDkHbJ31UxwbBMQiaCwpD/XEKu+pOoIeFYcmrfQ1Bcfg5cnCYJCwbX8IQt1Y4XXkkbdgBviSRsbeyseZ637qC6Mjg3+6/byIHNZzGs4dFl8PIIbon6jaqxlhgNc9/hCSa1jvlEwDotE66+DU/LgYMzDTrpWFFxwSGiecRu3zlSIqYLH0Q2XCDQNpoL+is2KIC80qHZAdbFZXhMLqkJ1GaVDGbtrXrjEioipz+BEX6ERdA6DZYqh//kwXI8Hs88chc5eKZMqpKwwD16ELEfXevI2Niwph55M= ruslan@netology"

          
        